# Generated by Django 3.0.3 on 2020-02-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='response_to',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='socialnetwork.Comment'),
        ),
    ]
