# Generated by Django 3.0.3 on 2020-02-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_auto_20200226_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_input_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_input_text',
        ),
    ]
